# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "lb1" do |lb1|
    lb1.vm.box = "ubuntu/xenial64"
    lb1.vm.network "private_network", ip: "192.168.0.2", netmask: "255.255.254.0"
    lb1.vm.network "forwarded_port", guest: 80, host: 8080
    lb1.vm.network "forwarded_port" , guest: 22, host: 2323, id: 'ssh'
    lb1.vm.provision "shell", path: "script.sh"
    lb1.vm.provider "virtualbox" do |vb1|
      vb1.gui = false
      vb1.name = "Load Balancer"
      vb1.cpus = 1
      vb1.memory = 1024
    end
  end
  config.vm.define "srv1" do |srv1|
    srv1.vm.box = "ubuntu/xenial64"
    srv1.vm.network "private_network", ip: "192.168.0.3", netmask: "255.255.254.0"
    srv1.vm.network "forwarded_port", guest: 80, host: 8081
    srv1.vm.network "forwarded_port" , guest: 22, host: 2424, id: 'ssh'
    srv1.vm.provision "shell", path: "script.sh"
    srv1.vm.provider "virtualbox" do |vb2|
      vb2.gui = false
      vb2.name = "Server 1"
      vb2.cpus = 1
      vb2.memory = 1024
    end
  end
end
